apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app-deployment
  labels:
    app: vprofile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-app
  template:
    metadata:
      labels:
        app: vprofile-app
    spec:
      containers:
        - name: app
          image: ivahuman/vprofile-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "vprofile-db-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "vprodbpass"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: vprofile-app-service
spec:
  type: LoadBalancer
  selector:
    app: vprofile-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
