apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-db-deployment
  labels:
    app: vprofile-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-db
  template:
    metadata:
      labels:
        app: vprofile-db
    spec:
      containers:
        - name: db
          image: ivahuman/vprofile-db:latest # تصویر Docker دیتابیس
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password" # گذرواژه دیتابیس
            - name: MYSQL_DATABASE
              value: "vprofile"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: vprofile-db-service
spec:
  type: ClusterIP
  selector:
    app: vprofile-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
